# Generated by Django 4.1.6 on 2023-03-10 12:24

import Test.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='person',
            managers=[
                ('objects', Test.managers.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='testing',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='SLUG'),
        ),
    ]
