# Generated by Django 4.1.6 on 2023-03-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0002_alter_person_managers_alter_testing_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trying',
            name='submit_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
