# Generated by Django 4.1.6 on 2023-03-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0002_alter_answer_trying'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='SLUG'),
        ),
    ]
