# Generated by Django 4.1.6 on 2023-03-10 17:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0003_alter_trying_submit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trying',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='trying',
            name='submit_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
