# Generated by Django 4.1.6 on 2023-03-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0003_alter_person_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(default=1, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
