# Generated by Django 4.1.6 on 2023-03-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0006_answer_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='trying',
            name='mark_percents',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(blank=True),
        ),
    ]
